#!/bin/bash
echo .
echo .
echo .
echo killing any remaining server processes 
echo .
echo .
echo .
{ # kill remaining processes and supress output
	pkill otp_enc_d 
	pkill otp_dec_d
} &> /dev/null

echo removing files
echo .
echo .
echo .
{ # remove old files and supress output
	rm otp_enc
	rm otp_enc_d
	rm otp_dec
	rm otp_dec_d 
	rm keygen 
	rm key20 
	rm key70000 
	rm cipher* 
	rm plaintext*_a 
} &> /dev/null

compile new files 
echo compiling new files
echo .
echo .
echo .
gcc otp_enc.c -o otp_enc -Wall
gcc otp_enc_d.c -o otp_enc_d -Wall
gcc otp_dec.c -o otp_dec -Wall
gcc otp_dec_d.c -o otp_dec_d -Wall
gcc keygen.c -o keygen -Wall
